services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - mysql
